language: C

matrix:
  include:
    - os: linux
      env: PYTHON_VERSION=2.7
    - os: linux
      env: PYTHON_VERSION=3.5
    - os: linux
      env: PYTHON_VERSION=3.6

    - osx_image: xcode8.3
      env:
        - PYTHON_VERSION=2.7
    - osx_image: xcode8.3
      env:
        - PYTHON_VERSION=3.5
    - osx_image: xcode8.3
      env:
        - PYTHON_VERSION=3.6

sudo: true 

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export OS="MacOSX";
      export py=$PYTHON_VERSION;
    else
      export OS="Linux";
      export py=$PYTHON_VERSION;
    fi
  - if [[ "$py" == "2.7_with_system_site_packages" ]]; then
      export py="2.7";
    fi
  - if [[ "${py:0:1}" == '2' ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-${OS}-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-${OS}-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - |
      if [[ "${py:0:1}" == "3" ]]; then
        PYFLAKES="pyflakes=1.0.0"
      else
        PYFLAKES="pyflakes=0.9.0"
      fi
  - echo $PYTHON_VERSION
  - travis_wait conda create -q -n test-environment python=$PYTHON_VERSION colorama numpy scipy matplotlib obspy flake8 mock coverage bottleneck pyproj
  - source activate test-environment
  - travis_wait pip install pep8-naming pytest pytest-cov pytest-pep8 pytest-xdist coverage codecov Cython
  - pip freeze
  - conda list
  # done installing dependencies
  - git version
  - git clone https://github.com/avuan/PyMPA37

before_script:
  - chmod +x ./*.dir/*.py

script:
   - cd ./download_data.dir
   - ./download_eida_ingv.py
   - ./download_inventory_ingv.py
   - cd ../trim_templates.dir
   - ./trim_templates4.1.py
   - cd ../calc_ttimes.dir
   - ./calcTT06.py
   - cd ../pympa38.dir
   - ./pympa40mac.py 
   - cd ../postproc.dir
   - ./postproc37.sh  
   - cd ../verify_detection.dir
   #- ./verify_detection02.py
   - ./verify_detection03.py
   
after_success:
  # Check how much code is actually tested and send this report to codecov
  #- mv .coverage ../.coverage.empty
  #- cd ..
  #- coverage combine
  #- codecov

notifications:
  email:
    recipients:
      - avuan@inogs.it
    on_success: never # default: change
    on_failure: always # default: always
